### ISSUE TITLE
missing source data on the report page

### ISSUE THREAD

**Issue by zhihaining** [jenkinsci/llvm-cov-plugin#4]
I'm also trying llvm-cov-plugin 1.0.0-alpha-2 and Code Coverage API Plugin 1.0.10

Under pipeline->post->always the llvmAdapter is defined
/* publish llvm coverage report*/ publishCoverage adapters: [llvmAdapter('UnittestsReport/Report.json')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')

There is also no error or waning in Jenkins log, but no source file was shown on the report page:
![grafik](https://user-images.githubusercontent.com/36398501/58802688-19adde80-860e-11e9-8b23-470d0f2eadad.png)

logs of publishCoverage:

    [Pipeline] publishCoverage
    Publishing Coverage report....
    A total of 1 reports were found
    Source File Navigation is enabled - Current level: STORE_LAST_BUILD
    0 source files need to be copied

I've created the [Report.json](https://github.com/jenkinsci/llvm-cov-plugin/files/3247598/Report.json.zip) with llvm-cov-6.0

**Comment by cizezsy** [comment]
Fix in #7, and will release a new version, thanks~
