### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by dmateja** [jenkinsci/llvm-cov-plugin#5]
Copy from jenkinsci/code-coverage-api-plugin#69
Now I just have to figure out why I don't have sources for llvm '0 source files need to be copied'
I have just added clangcoverage32.json - do you have any suggestion? (new Jenkinsfile, clangcoverage32.json, llvm1.jpg, llvm2.jpg).
[link to resources](https://drive.google.com/drive/folders/1DaE_XFQCKF0SO5jBrOLhzbDOT5k76cPQ)

**Comment by cizezsy** [comment]
Fix in #7, thanks :P
